name: MsetCCA-SSVEP
paradigms:
  - SSVEP

citations:
  - https://doi.org/10.1142/S0129065714500130

pipeline:
  - name: SSVEP_MsetCCA
    from: moabb.pipelines.classification
    parameters:
      freqs: { "12.0": 1, "8.57": 2, "6.67": 3, "5.45": 4 }
