name: MsetCCA-SSVEP
paradigms:
  - SSVEP

citations:
  - https://doi.org/10.1142/S0129065714500130

pipeline:
  - name: SSVEP_MsetCCA
    from: moabb.pipelines.classification
    parameters:
      freqs:
        {
          "8": 1,
          "9": 2,
          "10": 3,
          "11": 4,
          "12": 5,
          "13": 6,
          "14": 7,
          "15": 8,
          "8.2": 9,
          "9.2": 10,
          "10.2": 11,
          "11.2": 12,
          "12.2": 13,
          "13.2": 14,
          "14.2": 15,
          "15.2": 16,
          "8.4": 17,
          "9.4": 18,
          "10.4": 19,
          "11.4": 20,
          "12.4": 21,
          "13.4": 22,
          "14.4": 23,
          "15.4": 24,
          "8.6": 25,
          "9.6": 26,
          "10.6": 27,
          "11.6": 28,
          "12.6": 29,
          "13.6": 30,
          "14.6": 31,
          "15.6": 32,
          "8.8": 33,
          "9.8": 34,
          "10.8": 35,
          "11.8": 36,
          "12.8": 37,
          "13.8": 38,
          "14.8": 39,
          "15.8": 40,
        }
