name: SSVEP CCA

paradigms:
  - SSVEP

pipeline:
  - name: SSVEP_CCA
    from: moabb.pipelines.classification
    parameters:
      n_harmonics: 3
      interval: [1, 4]
      freqs: { "6.66": 1, "7.50": 2, "8.57": 3, "10.00": 4, "12.00": 5 }
